import {
  Calculator,
  Sigma,
  Shapes,
  Equal,
  BarChart3,
  FlaskConical,
  Dna,
  Atom,
  Trees,
  BookOpen,
  Globe,
  Banknote,
  Landmark,
  Scale,
  Brain,
  PenLine,
  Languages,
  Monitor,
  Code,
  Cog,
  Bot,
  Palette,
  Music,
  Ruler,
  Heart,
  Stethoscope,
  Briefcase,
  TrendingUp,
  type LucideIcon,
} from "lucide-react";

export interface SubjectEntry {
  name: string;
  category: string;
  icon: LucideIcon;
}

export const subjects: SubjectEntry[] = [
  { name: "Math", category: "Mathematics", icon: Calculator },
  { name: "Algebra", category: "Mathematics", icon: Sigma },
  { name: "Geometry", category: "Mathematics", icon: Shapes },
  { name: "Calculus", category: "Mathematics", icon: Equal },
  { name: "Statistics", category: "Mathematics", icon: BarChart3 },
  { name: "Biology", category: "Science", icon: Dna },
  { name: "Chemistry", category: "Science", icon: FlaskConical },
  { name: "Physics", category: "Science", icon: Atom },
  { name: "Environmental Science", category: "Science", icon: Trees },
  { name: "History", category: "Humanities", icon: Globe },
  { name: "Geography", category: "Humanities", icon: Landmark },
  { name: "Economics", category: "Humanities", icon: Banknote },
  { name: "Government", category: "Humanities", icon: Scale },
  { name: "Philosophy", category: "Humanities", icon: Brain },
  { name: "Psychology", category: "Humanities", icon: Brain },
  { name: "English", category: "Languages", icon: BookOpen },
  { name: "Spanish", category: "Languages", icon: Languages },
  { name: "French", category: "Languages", icon: Languages },
  { name: "Other Languages", category: "Languages", icon: PenLine },
  { name: "Computer Science", category: "Technology", icon: Monitor },
  { name: "Programming", category: "Technology", icon: Code },
  { name: "Engineering", category: "Technology", icon: Cog },
  { name: "Robotics", category: "Technology", icon: Bot },
  { name: "Art", category: "Creative Arts", icon: Palette },
  { name: "Music", category: "Creative Arts", icon: Music },
  { name: "Design", category: "Creative Arts", icon: Ruler },
  { name: "Health Science", category: "Health", icon: Heart },
  { name: "Anatomy", category: "Health", icon: Stethoscope },
  { name: "Business", category: "Business", icon: Briefcase },
  { name: "Finance", category: "Business", icon: TrendingUp },
];

export const categories = [
  "Mathematics",
  "Science",
  "Humanities",
  "Languages",
  "Technology",
  "Creative Arts",
  "Health",
  "Business",
] as const;
